# TiDB storage path. 
path = """ 
{{ #eachAlive bind.pd.members as |member| }}
  "{{member.sys.ip}}:{{member.cfg.client-port~}}"{{#unless @last}},{{/unless~}}
  {{/eachAlive}}
"""

# Rendered default.toml
{{toToml cfg}}
